const mongoose = require('mongoose');

// Import Counter model for atomic ID generation
require('./Counter');

const appointmentSchema = new mongoose.Schema({
  // Sequence numbers for Central OPD Registration reporting
  yearlyNo: { type: Number, required: false, index: true },
  monthlyNo: { type: Number, required: false, index: true },
  dailyNo: { type: Number, required: false, index: true },
  appointmentId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    sparse: true // Allow multiple null values, only enforce uniqueness on non-null values
  },
  // ✅ REMOVED: registrationNumber field (using appointmentId instead)
  patient: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Patient',
    required: true
  },
  doctor: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Doctor',
    required: false
  },
  room: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Room',
    required: false
  },
  department: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Department',
    required: false
  },
  appointmentDate: {
    type: Date,
    required: true,
    default: Date.now
  },
  // Normalized day (YYYY-MM-DD) for uniqueness per day
  appointmentDay: {
    type: String,
    index: true
  },
  appointmentTime: {
    type: String,
    required: true,
    default: function() {
      return new Date().toLocaleTimeString('en-GB', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
      });
    }
  },
  duration: {
    type: Number,
    default: 30, // minutes
    min: 15,
    max: 120
  },
  reason: {
    type: String,
    required: true
  },
  status: {
    type: String,
    enum: ['Scheduled', 'Confirmed', 'In Progress', 'Completed', 'Cancelled', 'No Show'],
    default: 'Scheduled'
  },
  type: {
    type: String,
    enum: ['Consultation', 'Follow-up', 'Emergency', 'Routine Check-up'],
    default: 'Consultation'
  },
  notes: {
    type: String
  },
  // Add weight field for appointment-specific data
  weightKg: {
    type: Number,
    min: 0
  },
  prescription: {
    medicines: [{
      name: String,
      dosage: String,
      frequency: String,
      duration: String,
      instructions: String
    }],
    advice: String
  },
  followUpDate: {
    type: Date
  },
  // Follow-up tracking fields
  isFollowUp: {
    type: Boolean,
    default: false
  },
  followUpCompleted: {
    type: Boolean,
    default: false
  },
  // New registration completion tracking
  newRegistrationCompleted: {
    type: Boolean,
    default: false
  },
  consultationFee: {
    type: Number,

  },
  paymentMethod : {
    type: String,
     enum: ['Cash', 'UPI'],
    default: 'Cash',
    required: true,
  },
  isPaid: {
    type: Boolean,
    default: false
  },
  // Embedded edit history for appointments
  editHistory: [{
    editedAt: { type: Date, default: Date.now },
    editedBy: { type: String },
    changes: { type: mongoose.Schema.Types.Mixed }
  }],
  editCount: { type: Number, default: 0 }
}, {
  timestamps: true
});

// Generate appointment ID and registration number automatically with atomic counter and retry logic
appointmentSchema.pre('save', async function(next) {
  try {
    // Ensure normalized appointmentDay is set for per-day uniqueness
    try {
      const d = this.appointmentDate ? new Date(this.appointmentDate) : new Date();
      if (!isNaN(d.getTime())) {
        const day = d.toISOString().slice(0, 10);
        this.appointmentDay = day;
      }
    } catch {}

    // Generate appointment ID if not exists using CounterService
    if (!this.appointmentId) {
      console.log('🔢 Generating appointment ID...');

      try {
        // Use CounterService for atomic operations with built-in retry logic
        const CounterService = require('../services/counter-service');
        const currentYear = new Date().getFullYear();
        const counterName = `appointmentId_${currentYear}`;

        const result = await CounterService.getNextValue(counterName, 'APT', 6);
        this.appointmentId = result.formattedId;
        console.log(`✅ Generated appointment ID: ${this.appointmentId} for year ${currentYear} (Counter: ${result.value})`);

      } catch (error) {
        console.error('❌ Error generating appointment ID with CounterService:', error);
        // Fallback: use timestamp + random number
        const timestamp = Date.now();
        const random = Math.floor(Math.random() * 1000);
        this.appointmentId = `APT${timestamp}${random}`;
        console.log('🔄 Using fallback appointment ID:', this.appointmentId);
      }
    }

    // ✅ REMOVED: Registration number generation (using appointmentId instead)

    next();
  } catch (error) {
    console.error('❌ Error generating appointment ID:', error);
    next(error);
  }
});

// Unique index to prevent multiple appointments per patient per day
appointmentSchema.index({ patient: 1, appointmentDay: 1 }, { unique: true, partialFilterExpression: { appointmentDay: { $exists: true } } });


// Indexes to speed up Central OPD report range scans and status filtering
appointmentSchema.index({ createdAt: 1 });
appointmentSchema.index({ createdAt: 1, status: 1 });

module.exports = mongoose.model('Appointment', appointmentSchema);
