import { Injectable } from '@angular/core';
import html2canvas from 'html2canvas';
import { DefaultLabConfigService } from './default-lab-config.service';

@Injectable({
  providedIn: 'root'
})
export class ImageGeneratorService {

  constructor(private defaultLabConfig: DefaultLabConfigService) { }

  /**
   * Convert HTML element to image blob
   * @param element HTML element to convert
   * @param options html2canvas options
   * @returns Promise<Blob> Image blob
   */
  async htmlToImage(element: HTMLElement, options?: any): Promise<Blob> {
    const defaultOptions = {
      backgroundColor: '#ffffff',
      scale: 2, // Higher quality
      useCORS: true,
      allowTaint: true,
      width: element.scrollWidth,
      height: element.scrollHeight
    };

    const finalOptions = { ...defaultOptions, ...options };

    try {
      const canvas = await html2canvas(element, finalOptions);
      
      return new Promise((resolve) => {
        canvas.toBlob((blob) => {
          if (blob) {
            resolve(blob);
          } else {
            throw new Error('Failed to generate image blob');
          }
        }, 'image/png', 0.9);
      });
    } catch (error) {
      console.error('❌ Error generating image:', error);
      throw error;
    }
  }

  /**
   * Generate report image from test report data
   * @param reportData Report data object
   * @returns Promise<Blob> Image blob
   */
  async generateReportImage(reportData: any): Promise<Blob> {
    // Create a temporary HTML element with report content
    const reportElement = this.createReportHTML(reportData);
    
    // Add to DOM temporarily
    document.body.appendChild(reportElement);
    
    try {
      // Generate image
      const imageBlob = await this.htmlToImage(reportElement, {
        width: 800,
        height: 1000,
        backgroundColor: '#ffffff'
      });
      
      return imageBlob;
    } finally {
      // Remove from DOM
      document.body.removeChild(reportElement);
    }
  }

  /**
   * Create HTML element for report
   * @param reportData Report data object
   * @returns HTMLElement
   */
  private createReportHTML(reportData: any): HTMLElement {
    const div = document.createElement('div');
    div.style.cssText = `
      width: 800px;
      padding: 40px;
      background: white;
      font-family: Arial, sans-serif;
      position: absolute;
      left: -9999px;
      top: -9999px;
    `;

    div.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #2c3e50; margin: 0; font-size: 24px;">PATHOLOGY TEST REPORT</h1>
        <p style="color: #666; margin: 5px 0;">Hospital Management System</p>
      </div>

      <div style="border: 2px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 15px 0; font-size: 16px;">Patient Information</h3>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 14px;">
          <div><strong>Name:</strong> ${reportData.patientName}</div>
          <div><strong>Receipt No:</strong> ${reportData.receiptNo}</div>
          <div><strong>Age:</strong> ${reportData.age}</div>
          <div><strong>Gender:</strong> ${reportData.gender}</div>
          <div><strong>Date:</strong> ${new Date(reportData.reportDate).toLocaleDateString('en-IN')}</div>
          <div><strong>Lab No:</strong> ${reportData.labYearlyNo}</div>
        </div>
      </div>

      <div style="border: 2px solid #e5e7eb; border-radius: 8px; padding: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 15px 0; font-size: 16px;">Test Results</h3>
        ${this.formatTestResultsHTML(reportData.testResults)}
      </div>

      <div style="text-align: center; margin-top: 30px; font-size: 12px; color: #666;">
        <p>Generated by Hospital Management System</p>
        <p>For any queries, contact the laboratory</p>
      </div>
    `;

    return div;
  }

  /**
   * Format test results as HTML
   * @param testResults Array of test results
   * @returns HTML string
   */
  private formatTestResultsHTML(testResults: any[]): string {
    if (!testResults || testResults.length === 0) {
      return '<p>No test results available</p>';
    }

    let html = '';
    
    // Group by category
    const categories = new Set<string>();
    testResults.forEach(test => {
      categories.add(test.category || 'GENERAL');
    });

    Array.from(categories).forEach(category => {
      html += `<div style="margin-bottom: 20px;">`;
      html += `<h4 style="color: #3b82f6; margin: 0 0 10px 0; font-size: 14px;">${category}</h4>`;
      
      const testsInCategory = testResults.filter(test => 
        (test.category || 'GENERAL') === category
      );
      
      testsInCategory.forEach(test => {
        html += `<div style="margin-bottom: 15px; padding: 10px; background: #f8f9fa; border-radius: 4px;">`;
        html += `<h5 style="margin: 0 0 8px 0; color: #2c3e50; font-size: 13px;">${test.testName}</h5>`;
        
        if (test.parameters && test.parameters.length > 0) {
          html += `<table style="width: 100%; border-collapse: collapse; font-size: 12px;">`;
          html += `<thead><tr style="background: #e5e7eb;">
                    <th style="padding: 5px; text-align: left; border: 1px solid #d1d5db;">Test</th>
                    <th style="padding: 5px; text-align: left; border: 1px solid #d1d5db;">Result</th>
                    <th style="padding: 5px; text-align: left; border: 1px solid #d1d5db;">Unit</th>
                    <th style="padding: 5px; text-align: left; border: 1px solid #d1d5db;">Normal Range</th>
                   </tr></thead><tbody>`;
          
          test.parameters.forEach((param: any) => {
            if (param.result) {
              const statusColor = this.getStatusColor(param.status);
              html += `<tr style="background: ${statusColor};">
                        <td style="padding: 5px; border: 1px solid #d1d5db;">${param.name}</td>
                        <td style="padding: 5px; border: 1px solid #d1d5db; font-weight: bold;">${param.result}</td>
                        <td style="padding: 5px; border: 1px solid #d1d5db;">${param.unit || ''}</td>
                        <td style="padding: 5px; border: 1px solid #d1d5db;">${param.displayInReport || param.normalRange}</td>
                       </tr>`;
              
              // Sub-parameters
              if (param.subParameters) {
                param.subParameters.forEach((subParam: any) => {
                  if (subParam.result) {
                    const subStatusColor = this.getStatusColor(subParam.status);
                    html += `<tr style="background: ${subStatusColor};">
                              <td style="padding: 5px; border: 1px solid #d1d5db; padding-left: 15px;">- ${subParam.name}</td>
                              <td style="padding: 5px; border: 1px solid #d1d5db; font-weight: bold;">${subParam.result}</td>
                              <td style="padding: 5px; border: 1px solid #d1d5db;">${subParam.unit || ''}</td>
                              <td style="padding: 5px; border: 1px solid #d1d5db;">${subParam.displayInReport || subParam.normalRange}</td>
                             </tr>`;
                  }
                });
              }
            }
          });
          
          html += `</tbody></table>`;
        }
        
        html += `</div>`;
      });
      
      html += `</div>`;
    });

    return html;
  }

  /**
   * Get background color based on test result status
   * @param status Test result status
   * @returns CSS color value
   */
  private getStatusColor(status: string): string {
    switch (status) {
      case 'normal': return '#f0fdf4';
      case 'high': return '#fef2f2';
      case 'low': return '#fffbeb';
      case 'critical': return '#fef2f2';
      default: return '#ffffff';
    }
  }

  /**
   * Get unique categories from test results
   * @param testResults Array of test results
   * @returns Array of unique categories
   */
  private getUniqueCategories(testResults: any[]): string[] {
    const categories = new Set<string>();
    testResults.forEach(test => {
      categories.add(test.category || 'GENERAL');
    });
    return Array.from(categories);
  }

  /**
   * Generate professional pathology report image matching hospital format
   */
  async generatePathologyReportImage(reportData: any, labSettings?: any): Promise<Blob> {
    console.log('🖼️ Generating professional pathology report image...');

    // Create professional HTML template
    const reportElement = this.createProfessionalReportHTML(reportData, labSettings);

    // Add to DOM temporarily
    document.body.appendChild(reportElement);

    try {
      // Generate high-quality image
      const imageBlob = await this.htmlToImage(reportElement, {
        width: 850,
        height: 1200,
        backgroundColor: '#ffffff',
        scale: 2 // Higher quality
      });

      console.log('✅ Professional pathology report image generated');
      return imageBlob;
    } finally {
      // Remove from DOM
      document.body.removeChild(reportElement);
    }
  }

  /**
   * Create professional HTML template matching hospital format with dynamic lab logo
   */
  private createProfessionalReportHTML(reportData: any, labSettings?: any): HTMLElement {
    const div = document.createElement('div');
    div.style.cssText = `
      width: 850px;
      padding: 30px;
      background: white;
      font-family: 'Times New Roman', serif;
      position: absolute;
      left: -9999px;
      top: -9999px;
      box-sizing: border-box;
      line-height: 1.4;
    `;

    // Get lab info from settings or use defaults
    const labLogo = labSettings?.logoDataUrl || this.defaultLabConfig.getLabLogo();
    const labName = this.defaultLabConfig.getLabName(labSettings?.labName);
    const labAddress = this.defaultLabConfig.getLabAddress(labSettings?.addressLine1 || labSettings?.city);

    div.innerHTML = `
      <!-- Hospital Header with Dynamic Lab Logo -->
      <div style="border: 2px solid #000; padding: 20px; margin-bottom: 20px; position: relative; background: white;">
        <!-- Lab Logo -->
        <img src="${labLogo}" style="position: absolute; left: 25px; top: 25px; width: 60px; height: 60px; object-fit: contain;" alt="Lab Logo" />

        <!-- Lab Information -->
        <div style="text-align: center; margin-left: 100px; padding: 10px;">
          <h1 style="margin: 0 0 8px 0; font-size: 18px; font-weight: bold; color: #000; font-family: 'Times New Roman', serif;">${labName}</h1>
          <p style="margin: 5px 0; font-size: 14px; color: #000; font-family: 'Times New Roman', serif;">${labAddress}</p>
        </div>
      </div>

      <!-- Simple separator line -->
      <div style="border-top: 1px solid #000; margin: 15px 0;"></div>

      <!-- Professional Patient Information Table -->
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 25px; font-size: 11px; border: 2px solid #000;">
        <tr>
          <td style="border: 1px solid #000; padding: 10px; width: 18%; background: #f8f9fa; font-weight: 600;">Patient Name :</td>
          <td style="border: 1px solid #000; padding: 10px; width: 25%; font-weight: bold; color: #2c3e50;">${reportData.patientName || 'N/A'}</td>
          <td style="border: 1px solid #000; padding: 10px; width: 18%; background: #f8f9fa; font-weight: 600;">Registration No. :</td>
          <td style="border: 1px solid #000; padding: 10px; width: 15%; font-weight: bold; color: #2c3e50;">${reportData.receiptNo || 'N/A'}</td>
          <td style="border: 1px solid #000; padding: 10px; width: 12%; background: #f8f9fa; font-weight: 600;">Date :</td>
          <td style="border: 1px solid #000; padding: 10px; width: 12%; font-weight: bold; color: #2c3e50;">${new Date(reportData.reportDate).toLocaleDateString('en-IN')}</td>
        </tr>
        <tr>
          <td style="border: 1px solid #000; padding: 10px; background: #f8f9fa; font-weight: 600;">Referred By :</td>
          <td style="border: 1px solid #000; padding: 10px; font-weight: bold; color: #2c3e50;">${reportData.doctorName || 'N/A'}</td>
          <td style="border: 1px solid #000; padding: 10px; background: #f8f9fa; font-weight: 600;">Age :</td>
          <td style="border: 1px solid #000; padding: 10px; font-weight: bold; color: #2c3e50;">${reportData.age || 'N/A'}</td>
          <td style="border: 1px solid #000; padding: 10px; background: #f8f9fa; font-weight: 600;">Gender :</td>
          <td style="border: 1px solid #000; padding: 10px; font-weight: bold; color: #2c3e50;">${reportData.gender || 'N/A'}</td>
        </tr>
        <tr>
          <td style="border: 1px solid #000; padding: 10px; background: #f8f9fa; font-weight: 600;">Lab Sr.No. :</td>
          <td style="border: 1px solid #000; padding: 10px; font-weight: bold; color: #2c3e50;">${reportData.labYearlyNo || 'N/A'}</td>
          <td style="border: 1px solid #000; padding: 10px; background: #f8f9fa; font-weight: 600;">IPD/OPD :</td>
          <td style="border: 1px solid #000; padding: 10px; font-weight: bold; color: #2c3e50;">OPD</td>
          <td style="border: 1px solid #000; padding: 10px; background: #f8f9fa;"></td>
          <td style="border: 1px solid #000; padding: 10px;"></td>
        </tr>
      </table>

      <!-- Professional Test Results Section -->
      <div style="margin-bottom: 40px;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 12px; margin-bottom: 15px; border-radius: 5px;">
          <h3 style="font-size: 16px; font-weight: bold; margin: 0; text-align: center; letter-spacing: 1px;">Test Results</h3>
        </div>
        ${this.formatProfessionalTestResultsHTML(reportData.testResults)}
      </div>

      <!-- Professional Signatures Section - Exact Reference Design -->
      <div style="margin-top: 80px; display: flex; justify-content: space-between; align-items: flex-start; padding: 0 80px;">
        <div style="text-align: center; width: 180px;">
          <p style="font-weight: bold; margin: 0 0 20px 0; font-size: 14px; color: #000;">Technician</p>
          <div style="border-bottom: 1px solid #000; width: 150px; margin: 0 auto;"></div>
          <div style="border-bottom: 1px dotted #666; width: 150px; margin: 5px auto 0 auto; height: 1px;"></div>
        </div>
        <div style="text-align: center; width: 180px;">
          <p style="font-weight: bold; margin: 0 0 20px 0; font-size: 14px; color: #000;">Pathologist</p>
          <div style="border-bottom: 1px solid #000; width: 150px; margin: 0 auto;"></div>
          <div style="border-bottom: 1px dotted #666; width: 150px; margin: 5px auto 0 auto; height: 1px;"></div>
        </div>
      </div>

      <!-- Medical Disclaimer - Exact Reference Design -->
      <div style="text-align: center; margin-top: 50px;">
        <p style="margin: 0 0 8px 0; font-size: 14px; font-weight: bold; color: #dc3545;">Not Valid for Medico-Legal Purpose.</p>
        <p style="margin: 0; font-size: 13px; font-weight: bold; color: #000;">Please Correlate Clinically.</p>
      </div>

      <!-- Professional Footer - Exact Reference Design -->
      <div style="text-align: center; margin-top: 30px; padding-top: 15px; border-top: 1px solid #dee2e6;">
        <p style="margin: 3px 0; font-size: 9px; color: #6c757d;">Page 1 of 1</p>
        <p style="margin: 3px 0; font-size: 9px; color: #6c757d;">Generated by Hospital Management System</p>
        <p style="margin: 3px 0; font-size: 8px; color: #6c757d;">${labName}${labAddress ? `, ${labAddress}` : ''}</p>
      </div>
    `;

    return div;
  }

  /**
   * Format test results with professional medical report layout
   */
  private formatProfessionalTestResultsHTML(testResults: any[]): string {
    if (!testResults || testResults.length === 0) {
      return '<div style="text-align: center; padding: 20px; color: #666; font-style: italic;">No test results available</div>';
    }

    let html = '';

    // Group by category
    const categories = new Set<string>();
    testResults.forEach(test => {
      categories.add(test.category || 'GENERAL');
    });

    Array.from(categories).forEach(category => {
      // Professional category header with medical styling
      html += `
        <div style="background: linear-gradient(135deg, #2980b9 0%, #3498db 100%); color: white; padding: 10px 15px; margin: 20px 0 0 0; font-weight: bold; font-size: 14px; border-radius: 5px 5px 0 0; text-transform: uppercase; letter-spacing: 0.5px;">
          ${category}
        </div>
      `;

      // Tests in this category
      const testsInCategory = testResults.filter(test =>
        (test.category || 'GENERAL') === category
      );

      testsInCategory.forEach(test => {
        if (test.parameters && test.parameters.length > 0) {
          // Professional test name header
          html += `
            <div style="background: #ecf0f1; padding: 8px 15px; margin: 0; font-weight: bold; font-size: 13px; color: #2c3e50; border-left: 4px solid #3498db;">
              ${test.testName}
            </div>
          `;

          // Professional parameters table with medical styling
          html += `
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 0; font-size: 11px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
              <thead>
                <tr style="background: linear-gradient(135deg, #34495e 0%, #2c3e50 100%); color: white;">
                  <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left; width: 35%; font-weight: 600;">Test</th>
                  <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center; width: 20%; font-weight: 600;">Result</th>
                  <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center; width: 15%; font-weight: 600;">Unit</th>
                  <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center; width: 30%; font-weight: 600;">Normal Range</th>
                </tr>
              </thead>
              <tbody>
          `;

          test.parameters.forEach((param: any, index: number) => {
            const bgColor = index % 2 === 0 ? '#ffffff' : '#f8f9fa';
            const isAbnormal = this.isResultAbnormal(param);
            const resultStyle = isAbnormal ? 'color: #e74c3c; font-weight: bold; background: #fdf2f2;' : 'font-weight: 600; color: #27ae60;';
            const borderColor = isAbnormal ? '#e74c3c' : '#bdc3c7';

            html += `
              <tr style="background: ${bgColor}; transition: all 0.3s ease;">
                <td style="border: 1px solid ${borderColor}; padding: 10px; color: #2c3e50; font-weight: 500;">${param.name || ''}</td>
                <td style="border: 1px solid ${borderColor}; padding: 10px; text-align: center; ${resultStyle}">${param.result || ''}</td>
                <td style="border: 1px solid ${borderColor}; padding: 10px; text-align: center; color: #7f8c8d; font-weight: 500;">${param.unit || ''}</td>
                <td style="border: 1px solid ${borderColor}; padding: 10px; text-align: center; color: #7f8c8d; font-size: 10px;">${param.normalRange || param.displayInReport || ''}</td>
              </tr>
            `;
          });

          html += `
              </tbody>
            </table>
          `;
        }
      });

      // Add spacing after each category
      html += `<div style="margin-bottom: 25px;"></div>`;
    });

    return html;
  }

  /**
   * Check if result is abnormal (simplified logic)
   */
  private isResultAbnormal(param: any): boolean {
    // This is a simplified check - can be enhanced based on actual normal ranges
    if (!param.result || !param.normalRange) return false;

    // Add your logic here to determine if result is abnormal
    // For now, returning false as placeholder
    return false;
  }

  /**
   * Download blob as file
   * @param blob File blob
   * @param filename File name
   */
  downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
